[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.7", features = [
	"derive",
	"zeroable_maybe_uninit",
	"zeroable_atomics",
] }
rand = { version = "^0.8.5" }
kas = { version = "0.14.1", features = ["wgpu"] }
kas-wgpu = { version = "0.14.1" }
env_logger = { version = "0.10" }
wgpu = { version = "0.18.0" }
ultraviolet = { version = "0.9.2" }
chrono = "0.4.38"
strum = "0.26.3"
strum_macros = "0.26.4"

[build-dependencies]
glob = "0.3"

[dev-dependencies]
test-case = { version = "^3.3.0" }

[profile.release]
debug = true
