[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pblade"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cgmath = {version = "^0.18", features = ["swizzle"] }
three-d = { version = "^0.16", features = ["egui-gui"] }
three-d-asset = { version = "0.7", features = [] }

[dev-dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"
