[package]
name = "paper-blade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pblade"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cgmath = {version = "^0.18", features = ["swizzle"] }
ron = "0.8.1"
ronda = "0.2.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.114"
three-d = { version = "^0.16", features = ["window"] }
three-d-asset = { version = "0.7", features = ["obj", "jpeg", "http", "serde"] }
winit = "0.28"

[dev-dependencies]
test-case = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
rand = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"
