[graph]
all-features = true

[advisories]
# for `instant` crate
ignore = ["RUSTSEC-2024-0384"]

[licenses]
allow = [
	"AGPL-3.0",
	"Apache-2.0",
	"Unicode-3.0",
	"MIT",
	"Zlib",
	"BSL-1.0",
	"MPL-2.0",
	"ISC",
	"CC0-1.0",
	"BSD-3-Clause",
	"BSD-2-Clause",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
